---
- name: Clone websites
  git:
    accept_hostkey: yes
    clone: yes
    update: yes
    dest: "{{ item.to }}"
    force: yes
    repo: "{{ item.src }}"
  with_items: "{{ static_web_folder_to_copy }}"

