---
- name: Clone websites
  git:
    accept_hostkey: yes
    clone: yes
    update: yes
    dest: "{{ item.to }}"
    force: yes
    repo: "{{ item.src }}"
  loop: "{{ static_web_folder_to_copy }}"

- name: Restrict .git access to root
  file:
    path: "{{ item.to }}/.git"
    mode: 0700
  loop: "{{ static_web_folder_to_copy }}"
